# based off of: https://github.com/pantheon-systems/fedora-test-kitchen-docker
#
# Use this with Chef and Test-Kitchen.
#
# Build:
#	    docker build -t fedora-test-kitchen:22 -f Dockerfile.chef-test-kitchen .
#
# In a `.kitchen.yml` file put the following:
#   ---
#   driver:
#     name: docker
#     privileged: true
#     run_command: "/usr/sbin/init"
# ...
#    platforms:
#     - name: fedora-22
#       driver_config:
#         dockerfile: test/Dockerfile.f22
#
# In a `test/Dockerfile.f22` file put the following single line:
#
#     FROM fedora-test-kitchen:22
#

FROM joemiller/fedora-systemd:22

# Chef
ADD https://www.opscode.com/chef/install.sh /install.sh
RUN bash /install.sh

# Packages
RUN dnf -y install sudo openssh-server openssh-clients curl dnf-plugins-core hostname

RUN dnf clean all

# OpenSSH Server Tweaks
RUN sed -i '/UsePAM/d'  /etc/ssh/sshd_config
RUN echo 'UsePrivilegeSeparation no' >> /etc/ssh/sshd_config
RUN echo 'UsePAM no' >> /etc/ssh/sshd_config
RUN systemctl enable sshd

# test-kitchen user (kitchen)
RUN useradd -d /home/kitchen -m -s /bin/bash kitchen
RUN echo "kitchen:kitchen" | chpasswd
RUN echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
